name: CI

on:
  push:
    branches-ignore: gh-pages
  pull_request:
    branches-ignore: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Run the tests
        run: ./gradlew check

      - name: Build application installation
        run: ./gradlew install

      - name: Fetch agora-official
        run: wget -c https://agora:nomic@mailman.agoranomic.org/archives/agora-official.mbox

      - name: Clean agora-official unicode
        run: cat agora-official.mbox | iconv -c -f UTF-8//TRANSLIT -t UTF-8//TRANSLIT > agora-official-clean.mbox

      - name: Generate reports
        run: |
          build/install/agora-proposal-parser/bin/agora-proposal-parser agora-official-clean.mbox proposals-out

      - name: Upload reports artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proposals
          path: proposals-out

  reports_deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch reports artifact
        uses: actions/download-artifact@v2
        with:
          name: proposals
          path: artifacts/proposals

      - name: Copy reports to gh-pages dir
        run: "cp -RT artifacts/proposals generation/gh-pages"

      - name: Deploy reports to Github Pages
        uses: crazy-max/ghaction-github-pages@v2.0.0
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: false
          build_dir: "generation/gh-pages"
          author: "ci-build <ci-build@randomcat.org>"
          commit_message: "CI Updates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
