name: CI

on:
  push:
    branches-ignore: gh-pages
  pull_request:
    branches-ignore: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Run the tests
        run: ./gradlew check

      - name: Build application installation
        run: ./gradlew install

      - name: Fetch agora-official
        run: wget -c https://agora:nomic@mailman.agoranomic.org/archives/agora-official.mbox

      - name: Fetch agora-business
        run: wget -c https://agora:nomic@mailman.agoranomic.org/archives/agora-business.mbox

      - name: Generate reports
        run: |
          build/install/agora-proposal-parser/bin/agora-proposal-parser agora-official.mbox agora-business.mbox proposals-out

      - name: Upload reports artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proposals
          path: proposals-out

  reports_deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch reports artifact
        uses: actions/download-artifact@v2
        with:
          name: proposals
          path: artifacts/proposals

      - name: Copy reports to gh-pages dir
        run: "cp -RT artifacts/proposals generation/gh-pages"

      - name: Deploy reports to Github Pages
        run: |
          # Set Git committer identity
          git config user.name "ci-build"
          git config user.email "ci-build@noreply.randomcat.org"
          
          # Clear the index
          EMPTY_TREE="$(git hash-object -t tree /dev/null)"
          git read-tree -- "$EMPTY_TREE"
          
          # Add site data to index
          git add generation/gh-pages
          
          git fetch origin gh-pages
          ORIG_SITE_TREE="$(git rev-parse origin/gh-pages^{tree})"
          NEW_SITE_TREE="$(git write-tree --prefix=generation/gh-pages)"                    
          
          if [ "$ORIG_SITE_TREE" != "$NEW_SITE_TREE" ]; then
            SITE_COMMIT="$(git commit-tree -p origin/gh-pages -m "CI Updates" -- "$NEW_SITE_TREE")"
            echo Updating GitHub pages site to commit "$SITE_COMMIT"
            git push origin "$SITE_COMMIT":gh-pages
          else
            echo Not updating GitHub pages site
          fi
